# templ_heroicons_generator/main.py

import sys
from .cli import main as run_cli_main # Import the main function from cli.py

def entry_point():
    """
    The main entry point for the command-line application.

    This function is intended to be called by the script generated by `pip`
    when the package is installed (as specified in `pyproject.toml` under
    `[project.scripts]`). It delegates execution to the main CLI handler
    in `cli.py`.
    """
    # The run_cli_main() function (which is cli.main) already handles
    # argument parsing, core logic execution, top-level exception handling,
    # and setting the sys.exit code. Therefore, this entry_point function
    # simply needs to call it.
    run_cli_main()

if __name__ == "__main__":
    """
    Allows the script to be run directly for development or testing purposes.
    
    This block is executed if this file (`main.py`) is run as the main program,
    for example, using `python -m templ_heroicons_generator.main` or
    `python path/to/templ_heroicons_generator/main.py`.
    
    It's also relevant if `templ_heroicons_generator/__main__.py` is set up
    to call this `entry_point` to enable `python -m templ_heroicons_generator`.
    """
    entry_point()